import Head from "next/head";

export function BrowserInfo() {
  return (
    <Head>
      <title>SOLID CALCULATOR V.1</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.svg" />
    </Head>
  );
}
