import Head from "next/head";
import Image from "next/image";

import { GButton } from "../components/gears/GButton";
import { Logo } from "../components/Logo";

import toast from "react-hot-toast";

export default function Home() {
  function handleGLogin() {
    toast.error("tbd");
  }
  return (
    <div className="bg-mountain opacity-90 bg-cover bg-no-repeat">
      <Head>
        <title>SOLID CALCULATOR V.1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main className="min-h-[90vh] flex-1 flex flex-col items-center justify-center">
        {/* call to action and sub box */}
        <div className="w-full flex items-center justify-center">
          {/*call to action*/}
          <div className="flex flex-col">
            <div className="flex flex-row items-center justify-center">
              <h1 className="text-[2.5rem]">
                <strong className="text-white">super calculadora</strong>
              </h1>
            </div>
            <p className="text-lg text-white leading-relaxed">
              Precificação não precisa ser um estresse.
            </p>
          </div>
        </div>
      </main>
      <footer className="flex flex-1 text-white px-8 border-t border-solid border-[#eaeaea] justify-center min-h-[10vh] items-center">
        <p>Powered by </p>
        <Logo />
      </footer>
    </div>
  );
}
